export default {
  "04f2558c": [() => import(/* webpackChunkName: "04f2558c" */ "@generated/docusaurus-plugin-content-docs/default/p/ur-docs-a2b.json"), "@generated/docusaurus-plugin-content-docs/default/p/ur-docs-a2b.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/ur-docs-a2b.json")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "232b566e": [() => import(/* webpackChunkName: "232b566e" */ "@site/docs/04.ros-2-fundamentals.mdx"), "@site/docs/04.ros-2-fundamentals.mdx", require.resolveWeak("@site/docs/04.ros-2-fundamentals.mdx")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "95695a56": [() => import(/* webpackChunkName: "95695a56" */ "@site/docs/05.vision-language-action-5vla.mdx"), "@site/docs/05.vision-language-action-5vla.mdx", require.resolveWeak("@site/docs/05.vision-language-action-5vla.mdx")],
  "9f359cc8": [() => import(/* webpackChunkName: "9f359cc8" */ "@site/docs/02.basics-of-humanoid-robotics.mdx"), "@site/docs/02.basics-of-humanoid-robotics.mdx", require.resolveWeak("@site/docs/02.basics-of-humanoid-robotics.mdx")],
  "a3981fa1": [() => import(/* webpackChunkName: "a3981fa1" */ "@site/docs/06.capstone-projects.mdx"), "@site/docs/06.capstone-projects.mdx", require.resolveWeak("@site/docs/06.capstone-projects.mdx")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a7ec6bd7": [() => import(/* webpackChunkName: "a7ec6bd7" */ "@site/docs/01.introduction-to-physical-ai.mdx"), "@site/docs/01.introduction-to-physical-ai.mdx", require.resolveWeak("@site/docs/01.introduction-to-physical-ai.mdx")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "fc6fed34": [() => import(/* webpackChunkName: "fc6fed34" */ "@site/docs/03.digital-twin-simulation.mdx"), "@site/docs/03.digital-twin-simulation.mdx", require.resolveWeak("@site/docs/03.digital-twin-simulation.mdx")],};
